# Generated by Django 2.2 on 2021-01-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.IntegerField(unique=True)),
                ('dept_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(db_index=True, max_length=100)),
                ('emp_dept', models.CharField(max_length=100)),
                ('emp_dob', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal_id', models.IntegerField(unique=True)),
                ('sal_net', models.IntegerField()),
                ('dept_name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='testapp.Department')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Employees')),
            ],
        ),
    ]
